//loaders
export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';
export const SIGNUP_ENABLE_LOADER = 'SIGNUP_ENABLE_LOADER';
export const SIGNUP_DISABLE_LOADER = 'SIGNUP_DISABLE_LOADER';
export const SEARCH_PROPERTY_ENABLE_LOADER = 'SEARCH_PROPERTY_ENABLE_LOADER';
export const SEARCH_PROPERTY_DISABLE_LOADER = 'SEARCH_DISABLE_PROPERTY_LOADER';
export const SEARCH_SINGLE_PROPERTY_ENABLE_LOADER =
  'SEARCH_SINGLE_PROPERTY_ENABLE_LOADER';
export const SEARCH_SINGLE_PROPERTY_DISABLE_LOADER =
  'SEARCH_SINGLE_PROPERTY_DISABLE_LOADER';
export const UPLOAD_PROPERTY_ENABLE_LOADER = 'UPLOAD_PROPERTY_ENABLE_LOADER';
export const UPLOAD_PROPERTY_DISABLE_LOADER = 'UPLOAD_PROPERTY_DISABLE_LOADER';

//theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOG_OUT = 'LOG_OUT';
export const SELLER_SIGN_UP_REQUEST = 'SELLER_SIGN_UP_REQUEST';
export const SELLER_SIGN_UP_RESPONSE = 'SELLER_SIGN_UP_RESPONSE';
export const SELLER_SIGN_UP_FAILED = 'SELLER_SIGN_UP_FAILED';
export const BUYER_SIGN_UP_REQUEST = 'BUYER_SIGN_UP_REQUEST';
export const BUYER_SIGN_UP_RESPONSE = 'BUYER_SIGN_UP_RESPONSE';
export const BUYER_SIGN_UP_FAILED = 'BUYER_SIGN_UP_FAILED';

//property
export const SEARCH_PROPERTY_REQUEST = 'SEARCH_PROPERTY_REQUEST';
export const SEARCH_PROPERTY_RESPONSE = 'SEARCH_PROPERTY_RESPONSE';
export const SEARCH_PROPERTY_FAILED = 'SEARCH_PROPERTY_FAILED';
export const SEARCH_SINGLE_PROPERTY_REQUEST = 'SEARCH_SINGLE_PROPERTY_REQUEST';
export const SEARCH_SINGLE_PROPERTY_RESPONSE =
  'SEARCH_SINGLE_PROPERTY_RESPONSE';
export const SEARCH_SINGLE_PROPERTY_FAILED = 'SEARCH_SINGLE_PROPERTY_FAILED';

export const UPLOAD_PROPERTY_REQUEST = 'UPLOAD_PROPERTY_REQUEST';
export const UPLOAD_PROPERTY_RESPONSE = 'UPLOAD_PROPERTY_RESPONSE';
export const UPLOAD_PROPERTY_FAILED = 'UPLOAD_PROPERTY_FAILED';

//user
export const SET_USER_TYPE = 'SET_USER_TYPE';
