import { StyleSheet } from 'react-native';
import config from 'app/config/styles';

export default StyleSheet.create({
  headerContainer: {
    borderRadius: 10,
    height: 110,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
  },
  headerTitle: {
    fontSize: 20,
    lineHeight: 27,
    color: 'white',
    fontFamily: config.fonts.FONT_BOLD,
    textTransform: 'uppercase',
  },
  container: {
    backgroundColor: 'white',
    flex: 1,
    padding: 10,
    paddingHorizontal: 20,
  },
  headingText: {
    marginTop: 15,
    marginBottom: 20,
    fontSize: 18,
    lineHeight: 23,
    fontFamily: config.fonts.FONT_BOLD,
  },
  addContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: config.color.COLOR_PRIMARY_ICON,
    padding: 10,
  },
  addText: {
    fontSize: 16,
    lineHeight: 17,
    color: config.color.COLOR_PRIMARY_ICON,
    marginLeft: 10,
    fontFamily: config.fonts.FONT_REGULAR,
  },
  item: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 40,
    borderRadius: 10,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
    padding: 10,
    margin: 0,
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
    minWidth: 98,
  },
  itemText: {
    fontSize: 16,
    lineHeight: 19,
    color: config.color.COLOR_WHITE,
    marginRight: 10,
    fontFamily: config.fonts.FONT_REGULAR,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smallCard: {
    width: '48%',
    height: 43,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 6,
    borderWidth: 0,
    borderRadius: 10,
    margin: 0,
  },
  optionText: {
    fontSize: 16,
    lineHeight: 21,
    color: config.color.COLOR_PRIMARY_ICON,
    marginLeft: 10,

    fontFamily: config.fonts.FONT_REGULAR,
  },
  sliderThumb: {
    height: 20,
    width: 20,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
    borderWidth: 3,
    borderColor: 'white',
    elevation: 20,
  },
  price: {
    marginTop: 10,
    fontSize: 16,
    lineHeight: 19,
    fontFamily: config.fonts.FONT_BOLD,
  },
  roomItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    height: 40,
    borderRadius: 10,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
    padding: 10,
    margin: 0,
    marginRight: 15,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,
    elevation: 6,
  },
  roomItemUnselected: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    height: 40,
    borderRadius: 10,
    backgroundColor: 'white',
    padding: 10,
    margin: 0,
    marginRight: 15,
    borderWidth: 1,
    borderColor: config.color.COLOR_PRIMARY_ICON,
  },
  itemunselectedText: {
    fontSize: 14,
    lineHeight: 17,
    color: config.color.COLOR_PRIMARY_ICON,
    marginLeft: 10,
    fontFamily: config.fonts.FONT_REGULAR,
  },
  btnContainer: {
    width: '100%',
    alignSelf: 'center',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.27,
    shadowRadius: 4.65,

    elevation: 6,
    borderRadius: 10,
  },

  btnTitle: {
    fontSize: 19,
    lineHeight: 24,
    fontFamily: config.fonts.FONT_BOLD,
  },
  btn: {
    height: 50,
    backgroundColor: config.color.COLOR_PRIMARY_BUTTON,
  },
  greyCard: {
    margin: 0,
    borderRadius: 10,
    height: 205,
    backgroundColor: '#e3e4f1',
    justifyContent: 'center',
  },
  uploadBtn: {
    height: 30,
    width: 159,
    alignSelf: 'center',
    borderRadius: 10,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
  },
  uploadBtnTitle: {
    fontSize: 14,
    lineHeight: 19,
    color: 'white',
    fontFamily: config.fonts.FONT_REGULAR,
  },
  imageCard: {
    width: 100,
    height: 70,
    padding: 0,
    borderRadius: 10,
    overflow: 'hidden',
    margin: 0,
    marginRight: 5,
  },
  footerImageCard: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  addPhotoText: {
    fontSize: 14,
    lineHeight: 19,
    color: config.color.COLOR_PRIMARY_ICON,
    fontFamily: config.fonts.FONT_REGULAR,
  },
  dollarText: {
    fontSize: 17,
    lineHeight: 25,
    color: config.color.COLOR_PRIMARY_ICON,
  },
  priceInput: {
    width: 109,
    height: 30,
    borderRadius: 10,
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: config.color.COLOR_PRIMARY_ICON,
    marginLeft: 10,
  },
  descriptionCard: {
    borderRadius: 10,
    backgroundColor: 'white',
    margin: 0,
    borderWidth: 1,
    borderColor: config.color.COLOR_PRIMARY_ICON,
  },
  descriptionText: {
    fontSize: 16,
    lineHeight: 19,
    color: config.color.COLOR_GREY_LABEL,
    fontFamily: config.fonts.FONT_REGULAR,
  },
});
