import { StyleSheet } from 'react-native';
import config from 'app/config/styles';

const styles = StyleSheet.create({
  header: {
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    backgroundColor: 'white',
  },
  headerTitle: {
    fontSize: 17,
    lineHeight: 19,
    color: '#36c683',
    fontWeight: '700',
  },
  container: { flex: 1, padding: 15, backgroundColor: 'white' },
  picker: {
    height: '100%',
    padding: 10,
    color: 'white',
  },

  pickerLabel: {
    fontSize: 14,
    lineHeight: 16,
    color: 'white',
    backgroundColor: 'red',
    height: '100%',
  },
  selectedLabelStyle: {
    fontSize: 14,
    lineHeight: 16,
    backgroundColor: 'red',
  },
  inputContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: '#e0e0e0',
    marginVertical: 10,
    paddingRight: 10,
    borderRadius: 3,
    marginHorizontal: 7,
    marginBottom: 15,
    height: 40,
  },

  inputLogo: {
    marginLeft: 15,
    color: '#999999',
  },
  input: {
    marginLeft: '5%',
    color: '#999999',
    fontWeight: 'bold',
    flex: 1,
  },
  price: {
    marginTop: 10,
    fontSize: 14,
    lineHeight: 19,
    fontFamily: config.fonts.FONT_BOLD,
  },
  priceContainer: {
    marginTop: 15,
    marginBottom: 20,
    fontSize: 18,
    lineHeight: 23,
    fontFamily: config.fonts.FONT_BOLD,
  },
  smallCard: {
    width: '48%',
    height: 43,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    elevation: 6,
    borderWidth: 0,
    borderRadius: 10,
    margin: 0,
  },
  pickerContainer: {
    borderRadius: 5,
    height: 40,
    marginHorizontal: 20,
    overflow: 'hidden',
    elevation: 10,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
    marginBottom: 20,
    paddingVertical: 10,
  },
  sliderThumb: {
    height: 20,
    width: 20,
    backgroundColor: config.color.COLOR_PRIMARY_ICON,
    borderWidth: 3,
    borderColor: 'white',
    elevation: 20,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  propertyText: {
    marginTop: 30,
    marginBottom: 20,
    fontSize: 18,
    lineHeight: 23,

    fontFamily: config.fonts.FONT_BOLD,
  },
  optionText: {
    fontSize: 16,
    lineHeight: 21,
    color: config.color.COLOR_PRIMARY_ICON,
    marginLeft: 10,

    fontFamily: config.fonts.FONT_REGULAR,
  },
  card: {
    borderWidth: 0,
    padding: 0,
    height: 220,
    marginHorizontal: 0,
    elevation: 3,
    borderRadius: 10,
    overflow: 'hidden',
    marginVertical: 20,
  },
  directionIcon: {
    height: 35,
    width: 35,
    position: 'absolute',
    bottom: '-10%',
    zIndex: 3,
    left: 20,
    borderRadius: 35,
    backgroundColor: 'orange',
    borderWidth: 2,
    borderColor: 'white',
    justifyContent: 'center',
  },
  locationName: {
    marginVertical: 2,
    fontSize: 18,
    lineHeight: 23,
    fontFamily: config.fonts.FONT_BOLD,
    color: config.color.COLOR_LABEL,
  },
  priceText: {
    fontSize: 18,
    lineHeight: 23,
    fontFamily: config.fonts.FONT_BOLD,
    color: config.color.COLOR_GREEN_LABEL,
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 15,
    justifyContent: 'space-between',
    width: '60%',
  },
  smallIconText: {
    fontSize: 10,
    marginLeft: 5,
    color: '#999999',
    fontFamily: config.fonts.FONT_BOLD,
  },
  smallIconContainer: { flexDirection: 'row', alignItems: 'center' },
});

export default styles;
